export * from "./create-log-normal-connected-scatter-group.function";
export * from "./create-normal-connected-scatter-group.function";
export * from "./create-normal-interpolator.function";
export * from "./create-normal-scale.function";
export * from "./create-normal-plot.function";
export * from "./create-normal-y-axis-tick-values.function";
export * from "./estimate-variance.function";
export * from "./fit-normal-distribution.function";
export * from "./get-gaussian-cumulative-distribution.function";
export * from "./get-gaussian-error.function";
export * from "./get-gaussian-probability-density.function";
export * from "./get-normal-quantile.function";
export * from "./get-inverse-gaussian-error.function";
export * from "./get-median-rank.function";
export * from "./to-normal-y-domain-value-from-range-value.function";
export { getFittedNormalDistributionLine } from "./get-fitted-normal-distribution-line.function";
export { resolveConnectedScatterPlotConfig } from "./resolve-connected-scatter-plot-config.function";
export { getNormalYCoordinate } from "./get-normal-y-coordinate.function";
export { createNormalInterpolatorWithBoundaries } from "./create-normal-interpolator-with-boundaries.function";
