name: Build and deploy NG 14

on:
  push:
    branches: [ support/ng-14 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        registry-url: 'https://registry.npmjs.org'

    - name: Install npm packages
      run: npm ci --loglevel=error

    - name: Test dgp-ng-app
      run: npm run dgp-ng-app:test:prod

    - name: Build dgp-ng-app
      run: npm run dgp-ng-app:build:prod

    - name: Build dgp-ng-docs
      run: npm run dgp-ng-docs:build:prod

    - name: Build dgp-ng-docking-layout
      run: npm run dgp-ng-docking-layout:build:prod

    - name: Build dgp-ng-drag-and-drop
      run: npm run dgp-ng-drag-and-drop:build:prod

    - name: Build dgp-ng-charts
      run: npm run dgp-ng-charts:build:prod

    - name: Build dgp-ng-paged-media
      run: npm run dgp-ng-paged-media:build:prod

    - name: Publish dgp-ng-app to npm
      run: npm run dgp-ng-app:publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: Publish dgp-ng-docs to npm
      run: npm run dgp-ng-docs:publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: Publish dgp-ng-docking-layout to npm
      run: npm run dgp-ng-docking-layout:publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: Publish dgp-ng-drag-and-drop to npm
      run: npm run dgp-ng-drag-and-drop:publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: Publish dgp-ng-charts to npm
      run: npm run dgp-ng-charts:publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: Publish dgp-ng-paged-media to npm
      run: npm run dgp-ng-paged-media:publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: build docs-app
      run: npm run docs-app:build:prod

    - name: Publish docs-app to firebase
      run: npm run docs-app:publish -- --only hosting:dgp-ng-app-14
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    - name: build dgp-labs
      run: npm run dgp-labs:build:prod

    - name: Publish dgp-labs to firebase
      run: npm run dgp-labs:publish
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
